apiVersion: apps/v1
kind: Deployment
metadata:
  name: quakewatch-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quakewatch
  template:
    metadata:
      labels:
        app: quakewatch
    spec:
      containers:
        - name: quakewatch
          image: adiyoshay681/quakewatch:latest
          ports:
            - containerPort: 5000

          env:
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: quakewatch-config
                  key: APP_MESSAGE

            - name: APP_MODE
              valueFrom:
                configMapKeyRef:
                  name: quakewatch-config
                  key: APP_MODE

            - name: SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: quakewatch-secret
                  key: SECRET_TOKEN

