apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: quakewatch
spec:
  type: {{ .Values.service.type }}
  selector:
    app: quakewatch
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: {{ .Values.service.nodePort }}

